### ISSUE TITLE
let cmake copy the folders in /bin to the compile folder [minor]

### ISSUE THREAD

**Issue by nieknooijens** [guusw/unnamed-sdvx-clone#13]
just as the title said, I currently have to copy over those folders manually or the game won't load. the make install script does copy them over, but I'd like to launch it from my C++ editor and therefore it runs from within the compile folder.

**Comment by GhettoGirl** [comment]
Your IDE should have a feature to run another executable or a wrapper script instead of the main binary, if not you can always create a symlink.

**Comment by guusw** [comment]
The linux makefiles compile to the bin folder. And both code blocks(linux) and visual studio(windows) can be set to have their working folder set to the bin folder. Doesn't really make sense to copy all the data to the Debug/Release folders since they don't change per configuration and it's handier to just have them in an obvious place.
